"""Add multi-provider AI support

Revision ID: 036123f3b71f
Revises: 1323702b33f8
Create Date: 2026-04-20 15:40:55.476734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '036123f3b71f'
down_revision: Union[str, None] = '1323702b33f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('groq_api_key', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('openai_api_key', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('anthropic_api_key', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('together_api_key', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('total_tokens_used', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('total_cost', sa.Float(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('monthly_cost', sa.Float(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('last_cost_reset', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_cost_reset')
    op.drop_column('users', 'monthly_cost')
    op.drop_column('users', 'total_cost')
    op.drop_column('users', 'total_tokens_used')
    op.drop_column('users', 'together_api_key')
    op.drop_column('users', 'anthropic_api_key')
    op.drop_column('users', 'openai_api_key')
    op.drop_column('users', 'groq_api_key')
    # ### end Alembic commands ###
