"""Add sources in messages table

Revision ID: 7b75456c4ab9
Revises: ef63572c89e1
Create Date: 2026-04-29 23:21:40.516690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b75456c4ab9'
down_revision: Union[str, None] = 'ef63572c89e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('metadata_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'metadata_json')
    # ### end Alembic commands ###
