"""Add RAG sources table

Revision ID: 7e812ae15618
Revises: 412f7076efd6
Create Date: 2026-04-27 19:50:33.315668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e812ae15618'
down_revision: Union[str, None] = '412f7076efd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rag_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('collection_name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.Enum('MANUAL', 'GITHUB', 'GOOGLE_DRIVE', name='sourcetype'), nullable=False),
    sa.Column('source_identifier', sa.String(length=500), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('auto_sync', sa.Boolean(), nullable=True),
    sa.Column('sync_interval_hours', sa.Integer(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='syncstatus'), nullable=True),
    sa.Column('last_sync_error', sa.String(length=1000), nullable=True),
    sa.Column('total_files', sa.Integer(), nullable=True),
    sa.Column('total_chunks', sa.Integer(), nullable=True),
    sa.Column('last_commit_sha', sa.String(length=255), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_rag_sources_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rag_sources'))
    )
    op.create_index(op.f('ix_rag_sources_collection_name'), 'rag_sources', ['collection_name'], unique=False)
    op.create_index(op.f('ix_rag_sources_id'), 'rag_sources', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rag_sources_id'), table_name='rag_sources')
    op.drop_index(op.f('ix_rag_sources_collection_name'), table_name='rag_sources')
    op.drop_table('rag_sources')
    # ### end Alembic commands ###
