"""Adjusted users table

Revision ID: b43727bbf5ad
Revises: 4f2d99b6e794
Create Date: 2026-04-18 13:16:34.553448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b43727bbf5ad'
down_revision: Union[str, None] = '4f2d99b6e794'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('date_of_birth', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('bio', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('tags', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tags')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'website')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'date_of_birth')
    op.drop_column('users', 'age')
    # ### end Alembic commands ###
